### ISSUE TITLE
Dependency on VHS

### ISSUE THREAD

**Issue by ayacoo** [svewap/videos#6]
https://github.com/WapplerSystems/videos/blob/release/v11/Resources/Private/Partials/fluid_styled_content/Media/Rendering/Video.html
https://github.com/WapplerSystems/videos/blob/release/v11/Resources/Private/Partials/fluid_styled_content/Media/Type/Video.html

VHS is used. Either the dependency would have to be added to the composer or the templates would have to be adapted.

**Comment by IchHabRecht** [comment]
Actually https://github.com/WapplerSystems/videos/blob/release/v11/Resources/Private/Partials/fluid_styled_content/Media/Rendering/Video.html uses the dependency and would need proper adjustment if the dependency should be removed.

**Comment by svewap** [comment]
I will write an own ViewHelper to be able to remove the vhs viewhelper
